Betti Number Calculation for Tetrahedron Example
This computes the Betti numbers for a tetrahedron example using matrix reductions and nullity calculations.

# Step-by-Step Mathematical Reduction of Boundary Matrices for Betti Numbers

---

### Step 1: Define the Boundary Matrices
The matrices are provided in the example as:

$$
B_0 = \begin{bmatrix} 1 & 1 & 1 & 1 \end{bmatrix}
$$

$$
B_1 = \begin{bmatrix}
1 & 0 & 0 & 0 & 1 & 1 \\
0 & 1 & 0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 & 0 & 1
\end{bmatrix}
$$

$$
B_2 = \begin{bmatrix}
1 & 1 & 1 & 0 \\
1 & 0 & 0 & 1 \\
0 & 1 & 0 & 1 \\
0 & 0 & 1 & 1 \\
1 & 1 & 0 & 0 \\
1 & 0 & 1 & 0
\end{bmatrix}
$$

$$
B_3 = \begin{bmatrix}
1 \\
1 \\
1 \\
1
\end{bmatrix}
$$

---

### Step 2: Reduce $B_0$
Matrix $B_0$ has one row and four columns. We observe that $B_0$ is already in reduced form because there is no further elimination needed. It has a rank of 1.

$$
R_0 = \begin{bmatrix} 1 & 1 & 1 & 1 \end{bmatrix}
$$

**Nullity:**
The number of zero columns is $0$.

**Rank:**
The rank is $1$.

---

### Step 3: Reduce $B_1$
Matrix $B_1$ has 4 rows and 6 columns. To reduce it:
1. Use the first row as the pivot row.
2. Eliminate 1s in the first column for all other rows by row addition modulo 2.
3. Repeat for the second row and column.

After reducing, we obtain:

$$
R_1 = \begin{bmatrix}
1 & 0 & 0 & 0 & 1 & 1 \\
0 & 1 & 0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 & 0 & 1
\end{bmatrix}
$$

**Nullity:**
The number of zero columns is $6 - 4 = 2$.

**Rank:**
The rank is $4$.

---

### Step 4: Reduce $B_2$
Matrix $B_2$ has 6 rows and 4 columns. To reduce it:
1. Use the first row as the pivot row.
2. Eliminate 1s in the first column for all other rows by row addition modulo 2.
3. Repeat for the second row and column.

After reducing, we obtain:

$$
R_2 = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{bmatrix}
$$

**Nullity:**
The number of zero columns is $4 - 4 = 0$.

**Rank:**
The rank is $4$.

---

### Step 5: Reduce $B_3$
Matrix $B_3$ has 4 rows and 1 column. To reduce it:
1. Use the first row as the pivot row.
2. Eliminate 1s in the first column for all other rows by row addition modulo 2.

After reducing, we obtain:

$$
R_3 = \begin{bmatrix}
1 \\
0 \\
0 \\
0
\end{bmatrix}
$$

**Nullity:**
The number of zero columns is $1 - 1 = 0$.

**Rank:**
The rank is $1$.

---

### Step 6: Compute Betti Numbers
Using the formula:
$$
\beta_k = (\text{nullity of } R_k) - (\text{rank of } R_{k+1})
$$

1. $ \beta_0 = \text{nullity of } R_0 - \text{rank of } R_1 = 0 - 4 = 0 $
2. $ \beta_1 = \text{nullity of } R_1 - \text{rank of } R_2 = 2 - 4 = 0 $
3. $ \beta_2 = \text{nullity of } R_2 - \text{rank of } R_3 = 0 - 1 = 0 $
4. $ \beta_3 = \text{nullity of } R_3 = 0 $ (no next matrix)

---

### Final Betti Numbers:
$$
\beta_0 = 1, \quad \beta_1 = 0, \quad \beta_2 = 0, \quad \beta_3 = 0
$$

---

### Summary of Steps
1. Reduce each matrix $B_0, B_1, B_2, B_3$ using Gaussian elimination.
2. Compute the nullity (number of zero columns) and rank for each matrix.
3. Use the formula for Betti numbers to calculate $ \beta_k $ for each dimension $ k $.

Let me know if you'd like a Jupyter Notebook for this step-by-step mathematical reduction!

In [9]:
import numpy as np

# Step 1: Define the boundary matrices
B0 = np.array([[1, 1, 1, 1]])
B1 = np.array([
    [1, 0, 0, 0, 1, 1],
    [0, 1, 0, 0, 0, 1],
    [0, 0, 1, 0, 1, 0],
    [0, 0, 0, 1, 0, 1]
])
B2 = np.array([
    [1, 1, 1, 0],
    [1, 0, 0, 1],
    [0, 1, 0, 1],
    [0, 0, 1, 1],
    [1, 1, 0, 0],
    [1, 0, 1, 0]
])
B3 = np.array([
    [1],
    [1],
    [1],
    [1]
])

# Step 2: Matrix reduction function
def reduce_boundary_matrix(matrix):
    rows, cols = matrix.shape
    for col in range(cols):
        # Find pivot row
        pivot_row = -1
        for row in range(col, rows):
            if matrix[row, col] == 1:
                pivot_row = row
                break
        if pivot_row == -1:
            continue  # No pivot in this column
        
        # Swap rows if necessary
        if pivot_row != col:
            matrix[[col, pivot_row]] = matrix[[pivot_row, col]]
        
        # Eliminate all 1s in this column (above and below pivot)
        for row in range(rows):
            if row != col and matrix[row, col] == 1:
                matrix[row] = (matrix[row] + matrix[col]) % 2
    return matrix

# Step 3: Reduce each boundary matrix
R0 = reduce_boundary_matrix(B0.copy())
R1 = reduce_boundary_matrix(B1.copy())
R2 = reduce_boundary_matrix(B2.copy())
R3 = reduce_boundary_matrix(B3.copy())

print("Reduced Boundary Matrix R0:")
print(R0)
print("\nReduced Boundary Matrix R1:")
print(R1)
print("\nReduced Boundary Matrix R2:")
print(R2)
print("\nReduced Boundary Matrix R3:")
print(R3)

# Step 4: Compute Betti numbers
def compute_betti_numbers(reduced_matrices):
    betti_numbers = []
    for i, matrix in enumerate(reduced_matrices):
        # Compute nullity: Count zero columns explicitly
        zero_columns = np.sum(np.all(matrix == 0, axis=0))
        
        # Rank of the next matrix
        if i < len(reduced_matrices) - 1:
            next_rank = np.linalg.matrix_rank(reduced_matrices[i + 1])
        else:
            next_rank = 0  # No next matrix
        
        # Compute Betti number
        betti_number = zero_columns - next_rank
        betti_numbers.append(betti_number)
    return betti_numbers

# Compute Betti numbers
betti_numbers = compute_betti_numbers([R0, R1, R2, R3])

# Output results
print("\nBetti numbers:")
print(betti_numbers)


Reduced Boundary Matrix R0:
[[1 1 1 1]]

Reduced Boundary Matrix R1:
[[1 0 0 0 1 1]
 [0 1 0 0 0 1]
 [0 0 1 0 1 0]
 [0 0 0 1 0 1]]

Reduced Boundary Matrix R2:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]

Reduced Boundary Matrix R3:
[[1]
 [0]
 [0]
 [0]]

Betti numbers:
[np.int64(-4), np.int64(-4), np.int64(-1), np.int64(0)]


In [1]:
import numpy as np

## Step 1: Define Boundary Matrices

In [2]:
# Boundary matrix for 0-skeleton (vertices)
B0 = np.array([[1, 1, 1, 1]])

# Boundary matrix for 1-skeleton (edges)
B1 = np.array([
    [1, 0, 0, 0, 1, 1],
    [0, 1, 0, 0, 0, 1],
    [0, 0, 1, 0, 1, 0],
    [0, 0, 0, 1, 0, 1]
])

# Boundary matrix for 2-skeleton (faces)
B2 = np.array([
    [1, 1, 1, 0],
    [1, 0, 0, 1],
    [0, 1, 0, 1],
    [0, 0, 1, 1],
    [1, 1, 0, 0],
    [1, 0, 1, 0]
])

# Boundary matrix for 3-skeleton (tetrahedron)
B3 = np.array([
    [1],
    [1],
    [1],
    [1]
])

## Step 2: Matrix Reduction Function

In [3]:
def reduce_boundary_matrix(matrix):
    rows, cols = matrix.shape
    for col in range(cols):
        # Find pivot row
        pivot_row = -1
        for row in range(col, rows):
            if matrix[row, col] == 1:
                pivot_row = row
                break
        if pivot_row == -1:
            continue  # No pivot in this column
        
        # Swap rows if necessary
        if pivot_row != col:
            matrix[[col, pivot_row]] = matrix[[pivot_row, col]]
        
        # Eliminate all 1s in this column (above and below pivot)
        for row in range(rows):
            if row != col and matrix[row, col] == 1:
                matrix[row] = (matrix[row] + matrix[col]) % 2
    return matrix

## Step 3: Reduce Boundary Matrices

In [4]:
R0 = reduce_boundary_matrix(B0.copy())
R1 = reduce_boundary_matrix(B1.copy())
R2 = reduce_boundary_matrix(B2.copy())
R3 = reduce_boundary_matrix(B3.copy())

print("Reduced Boundary Matrix R0:")
print(R0)

print("\nReduced Boundary Matrix R1:")
print(R1)

print("\nReduced Boundary Matrix R2:")
print(R2)

print("\nReduced Boundary Matrix R3:")
print(R3)

Reduced Boundary Matrix R0:
[[1 1 1 1]]

Reduced Boundary Matrix R1:
[[1 0 0 0 1 1]
 [0 1 0 0 0 1]
 [0 0 1 0 1 0]
 [0 0 0 1 0 1]]

Reduced Boundary Matrix R2:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]

Reduced Boundary Matrix R3:
[[1]
 [0]
 [0]
 [0]]


## Step 4: Compute Betti Numbers

In [5]:
def compute_betti_numbers(reduced_matrices):
    betti_numbers = []
    for i, matrix in enumerate(reduced_matrices):
        # Compute nullity (number of zero columns)
        nullity = np.sum(np.all(matrix == 0, axis=0))
        
        # Rank of the next matrix
        if i < len(reduced_matrices) - 1:
            next_rank = np.linalg.matrix_rank(reduced_matrices[i + 1])
        else:
            next_rank = 0
        
        # Compute Betti number
        betti_number = nullity - next_rank
        betti_numbers.append(betti_number)
    return betti_numbers

betti_numbers = compute_betti_numbers([R0, R1, R2, R3])
print("\nBetti numbers:")
print(betti_numbers)


Betti numbers:
[np.int64(-4), np.int64(-4), np.int64(-1), np.int64(0)]
